### ISSUE TITLE
installation fails with NPE when PluginManagement and <plugin> tags thereunder are present

### ISSUE THREAD

**Issue by StephanWald** [DwcJava/dwcj-install-bbj-lib#1]
The code scans for all <plugin> tags, and fails because those under <pluginmanagement> don't have a GroupID.
The plugin entries under plugin management should be ignored in this area:

https://github.com/DwcJava/dwcj-install-bbj-lib/blob/d08a282564861569c4e5a382ea78a19593ec7bc4/src/main/java/org/dwcj/installer/PomParser.java#L54-L56

**Comment by kevinhagel** [comment]
New work in the PomParser using XPath prevents this from happening.
