### ISSUE TITLE
Enhance Plugin to Automatically Handle and Transfer 'Provided' Dependencies

### ISSUE THREAD

**Issue by hyyan** [DwcJava/dwcj-install-bbj-lib#5]
This plugin does not manage provided dependencies. Currently, we do not upload the JAR files for these dependencies. We should enhance the automation to ensure that the plugin also transfers all the "provided" dependencies.

**Comment by kevinhagel** [comment]
the original ticket for #3 is probably invalid.
Change the includeScope=compile, this will ensure that provided and system scoped dependencies are fetched and made available for the dwcj project when deploy.  The dependency plugin also ensure the classpath works, such jars as we are discussing now can be used in the dwcj app without any classnotfoundexception.
